---
# tasks file for external-port-connectivity-validator-server
- name: Do not use proxy definitions
  include: with_no_proxy.yml
  when: (https_proxy is not defined or https_proxy | trim == '') and (http_proxy is not defined or http_proxy | trim == '')

- name: Use proxy definitions
  include: with_proxy.yml
  when: https_proxy is defined and https_proxy | trim != '' and http_proxy is defined and http_proxy | trim != ''
